version: 2.1

executors:
  docker-publisher:
    docker: 
      - image: circleci/buildpack-deps:stretch

jobs:
  docker-build-publish:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run: bash bin/deploy authenticate
      - run: bash bin/deploy build-and-publish

workflows:
  dockerfiles-pipeline:
    jobs:
      - docker-build-publish:
          filters:
            branches:
              only:
                - master
