name: Greetings

on: [pull_request_target, issues, workflow_dispatch]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - name: test env
      run: |
        env
    - name: get event file
      run: | 
        cat /home/runner/work/_temp/_github_workflow/event.json | jq
